name: downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL of the file
        required: true
        default: https://download-installer.cdn.mozilla.net/pub/firefox/releases/122.0.1/win64/en-US/Firefox%20Setup%20122.0.1.exe
      url_file_name:
        description: File name of the url
        required: true    
      file_name:
        description: File name of the file in the torrent
        required: true
        default: Firefox Setup 122.0.1.exe
      maximize_disk_space:
        description: Maximize disk space. Check if getting out of disk space error
        type: boolean

jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: inputs.maximize_disk_space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Setup torrenttools
        uses: AnimMouse/setup-appimage@v1
        with:
          name: torrenttools
          url: https://github.com/fbdtemme/torrenttools/releases/download/v0.6.2/torrenttools-0.6.2-linux-x86_64.AppImage

      - name: Download files
        run: |
          for i in $(seq -f "%03g" 1 18); do
            aria2c -x 16 -o "${{ inputs.url_file_name }}.$i" "${{ inputs.url }}.$i"
          done

      - name: List files
        run: ls -l

      - name: Rename files
        run: |
          for i in $(seq -f "%03g" 1 18); do
            mv "${{ inputs.url_file_name }}.$i" "${{ inputs.file_name }}.$i"
          done

      - name: List files
        run: ls -l

      - name: Combine files
        run: cat "${{ inputs.file_name }}".* > "${{ inputs.file_name }}"

      - name: List files
        run: ls -l

      - name: Split file
        if: $(du -b "${{ inputs.file_name }}" | cut -f1) -gt 1000000000
        run: split -b 1000m "${{ inputs.file_name }}" "${{ inputs.file_name }}."

      - name: List files
        run: ls -l

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.file_name }}
          path: |
            ${{ inputs.file_name }}.*
            !${{ inputs.file_name }}
